### ISSUE TITLE
welcome to the game

### ISSUE THREAD

**Issue by IMrcat** [client-cringe-my-ass-doxin-dunces/world-client-vr-chat#1]
Hi,
If you want to appeal your blacklist please contact me at Mr.cat#5455 
There We can talk about you and why your banned. Or you can act like a child 
Its really up to you. 

Thx for saying false info 
WC moderation

**Comment by Hacker1254** [comment]
Cope lol

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
and yet burner accounts exist

**Comment by IMrcat** [comment]
> and yet burner accounts exist

And yet you should talk to us were not scary people lmao :3

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
says the one who suggested this was a rat, didnt you notice that the account you kicked wasnt even verified, i already know you talked about changing the key its not hard to update the files here to address that all 

qoute
"@here hacker said to say change the update key sho"

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
anything ypu change will be instantly changed to mirror here and all without the hassle of tickets and the stupid degrading retard roles you asshats give for people just ating once in a ticket  not even a dm mind you an actual legitimate ticket even when there's documentation to @ after an hour i waited much longer within weeks. you are giving a free client and were thankful for your hardwork on such but you give the users a headache with your demeaning roles and obvious hypocrosy

**Comment by IMrcat** [comment]
So your complaining because of a joke role

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
a role that gets ated almost constantly and that you tell others to shit on

**Comment by IMrcat** [comment]
It hardly gets @? And two we don't?

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
uhuh

**Comment by IMrcat** [comment]
I mean you can prove me wrong at Mr.cat#5455

**Comment by client-cringe-my-ass-doxin-dunces** [comment]
open up your client to the public

this is more of a hassle than anyone needs to deal with

**Comment by Hacker1254** [comment]
💀

**Comment by IMrcat** [comment]
> open up your client to the public
> 
> this is more of a hassle than anyone needs to deal with
Ok i will when you stop acting like a child

**Comment by Hacker1254** [comment]
Cope
